version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: soccer_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123!
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
