spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soccer_db
    username: user
    password: password123!

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
